[package]
authors = ["Brayden Banks <bb010g@gmail.com>"]
name = "baimax"
version = "0.1.0"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Type-safe BAI serialization library for Rust"
repository = "https://github.com/bb010g/baimax.git"

[dependencies]
chrono = "0.2.25"
clippy = "*"
if_chain = "0.1.1"
lazy_static = "0.2.2"
nom = "2.0.1"
regex = "0.2.1"
void = "1.0.2"

[dependencies.penny]
git = "https://github.com/bb010g/penny.git"
